version: '{build}'

image:
- Visual Studio 2017
- Visual Studio 2015

configuration:
- Debug
- Release

platform:
- x64
- x86

init:
- set arch=
- if "%platform%"=="x64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

build_script:
- mkdir build && cd build
- cmake .. -G %generator% -DCMAKE_BUILD_TYPE=%configuration% -DDEV_MODE=ON
