dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:

    ##########################################################################
    # Clang on Linux
    ##########################################################################

    # Clang 3.6
    - os: linux
      dist: trusty
      compiler: clang
      env: CC=clang-3.6  CXX=clang++-3.6   BUILD_TYPE=Debug
      addons: &clang36
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.6 BUILD_TYPE=Release
      addons: *clang36

    # Clang 3.7
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.7  BUILD_TYPE=Debug
      addons: &clang37
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.7  BUILD_TYPE=Release
      addons: *clang37

    # Clang 3.8
    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.8  BUILD_TYPE=Debug
      addons: &clang38
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.8  BUILD_TYPE=Release
      addons: *clang38

    # Clang 3.9
    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.9  BUILD_TYPE=Debug
      addons: &clang39
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.9  BUILD_TYPE=Release
      addons: *clang39

    # Clang 4
    - os: linux
      compiler: clang
      env: COMPILER=clang++-4.0  BUILD_TYPE=Debug
      addons: &clang40
        apt:
          packages:
            - clang-4.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    - os: linux
      compiler: clang
      env: COMPILER=clang++-4.0  BUILD_TYPE=Release
      addons: *clang40

    # Clang 5
    - os: linux
      compiler: clang
      env: COMPILER=clang++-5.0  BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    - os: linux
      compiler: clang
      env: COMPILER=clang++-5.0  BUILD_TYPE=Release
      addons: *clang50

    # Clang 6.0
    - os: linux
      compiler: clang
      env: COMPILER=clang++-6.0  BUILD_TYPE=Debug
      addons: &clang60
        apt:
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    - os: linux
      compiler: clang
      env: COMPILER=clang++-6.0  BUILD_TYPE=Release
      addons: *clang60

    # Clang 7.0
    - os: linux
      compiler: clang
      env: COMPILER=clang++-7.0  BUILD_TYPE=Debug
      addons: &clang70
        apt:
          packages:
            - clang-7.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7.0

    - os: linux
      compiler: clang
      env: COMPILER=clang++-7.0  BUILD_TYPE=Release
      addons: *clang70

script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DDEV_MODE=ON
  - cmake --build . -- VERBOSE=1