os: linux
dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:

    # Clang 7.0
    - env: CC=clang-7 CXX=clang++-7  BUILD_TYPE=Debug
      addons: &clang70
        apt:
          packages:
            - clang-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: CC=clang-7 CXX=clang++-7  BUILD_TYPE=Release
      addons: *clang70

    # Clang 7.0
    - env: CC=clang-8 CXX=clang++-8  BUILD_TYPE=Debug
      addons: &clang80
        apt:
          packages:
            - clang-8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8


    - env: CC=clang-8 CXX=clang++-8  BUILD_TYPE=Release
      addons: *clang80

script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DDEV_MODE=ON
  - cmake --build . -- VERBOSE=1