language: cpp

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DALLOW_EXAMPLES=ON -DALLOW_TESTS=ON
  - cmake --build . -- VERBOSE=1

cache:
  - apt
  - ccache

matrix:
  include:

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    # GCC 4.9
    - os: linux
      dist: trusty
      env: COMPILER=g++-4.9 BUILD_TYPE=Debug
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      env: COMPILER=g++-4.9 BUILD_TYPE=Release
      addons: *gcc49


    # GCC 5
    - os: linux
      dist: trusty
      env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty
      env: COMPILER=g++-5 BUILD_TYPE=Release
      addons: *gcc5

    # GCC 6
    - os: linux
      dist: trusty
      env: COMPILER=g++-6 BUILD_TYPE=Debug
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty
      env: COMPILER=g++-6 BUILD_TYPE=Release
      addons: *gcc6

    # GCC 7
    - os: linux
      dist: trusty
      env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc7

    ##########################################################################
    # Clang on Linux
    ##########################################################################

    # Clang 3.6
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.6 BUILD_TYPE=Debug
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.6 BUILD_TYPE=Release
      addons: *clang36

    # Clang 3.7
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.7 BUILD_TYPE=Debug
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.7 BUILD_TYPE=Release
      addons: *clang37

    # Clang 3.8
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.8 BUILD_TYPE=Debug
      addons: &clang38
        apt:
          packages:
            - clang-3.8
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.8 BUILD_TYPE=Release
      addons: *clang38

    # Clang 3.9
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.9 BUILD_TYPE=Debug
      addons: &clang39
        apt:
          packages:
            - clang-3.9
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
    - os: linux
      dist: trusty
      env: COMPILER=clang++-3.9 BUILD_TYPE=Release
      addons: *clang39

    # Clang 4.0
    - os: linux
      dist: trusty
      env: COMPILER=clang++-4.0 BUILD_TYPE=Debug
      addons: &clang40
        apt:
          packages:
            - clang-4.0
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Release
      addons: *clang40

    # Clang 5.0
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release
      addons: *clang50

    # Clang 6.0
    - env: COMPILER=clang++-6.0 BUILD_TYPE=Debug
      addons: &clang60
        apt:
          packages:
            - clang-6.0
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - os: linux
      dist: trusty
      env: COMPILER=clang++-6.0 BUILD_TYPE=Release
      addons: *clang60

    # Clang 7.0
    - os: linux
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7 && BUILD_TYPE=Debug"

      addons: &clang70
        apt:
          packages:
            - clang-7
            - libclang-7-dev
            - llvm-7-dev
            - lld-7
            - libc++-7-dev
            - libc++abi-7-dev
            - cmake=2.\*
            - cmake-data=2.\*
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - os: linux
      dist: trusty
      env: COMPILER=clang++-7 BUILD_TYPE=Release
      addons: *clang70

    ##########################################################################
    # Clang on OSX
    # Travis seems to take longer to start OSX instances,
    # so leave this first for the overall build to be faster
    ##########################################################################

    # XCode 8.3
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.3
      compiler: clang

    # XCode 9.1
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9.1
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode9.1
      compiler: clang