dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:

    # Clang 7.0
    - os: linux
      dist: trusty
      env: CC=clang-7.0 CXX=clang++-7.0  BUILD_TYPE=Debug
      addons: &clang70
        apt:
          packages:
            - clang-7.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - os: linux
      dist: trusty
      env: CC=clang-7.0 CXX=clang++-7.0  BUILD_TYPE=Release
      addons: *clang70

    # Clang 8.0
    - os: linux
      dist: trusty
      env: CC=clang-8.0 CXX=clang++-8.0  BUILD_TYPE=Debug
      addons: &clang80
        apt:
          packages:
            - clang-8.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - os: linux
      dist: trusty
      env: CC=clang-8.0 CXX=clang++-8.0  BUILD_TYPE=Release
      addons: *clang80

script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DDEV_MODE=ON
  - cmake --build . -- VERBOSE=1