dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:

    # Clang 7.0
    - os: linux
      env: CC=clang-7.0 CXX=clang++-7.0  BUILD_TYPE=Debug
      addons: &clang70
        apt:
          packages:
            - clang-7.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - os: linux
      env: CC=clang-7.0 CXX=clang++-7.0  BUILD_TYPE=Release
      addons: *clang70

script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DDEV_MODE=ON
  - cmake --build . -- VERBOSE=1