on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          cfg:
            - { os: ubuntu-16.04, cpp-version: gcc-4.8 }
            - { os: ubuntu-16.04, cpp-version: gcc-5 }
            - { os: ubuntu-16.04, cpp-version: gcc-6 }
            - { os: ubuntu-16.04, cpp-version: gcc-7 }
            - { os: ubuntu-18.04, cpp-version: gcc-4.8 }
            - { os: ubuntu-18.04, cpp-version: gcc-5 }
            - { os: ubuntu-18.04, cpp-version: gcc-6 }
            - { os: ubuntu-18.04, cpp-version: gcc-7 }

    steps:
      - uses: actions/checkout@v2

      - run: |
          if ["$RUNNER_OS" == "Linux"]; then
             sudo apt install ${{ matrix.cfg.cpp-version }}
          fi