name: ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [
          {"COMPILER":"gcc-4.8","BUILD_TYPE":"Release","CXX_STANDARD":11},
          {"COMPILER":"gcc-4.8","BUILD_TYPE":"Debug","CXX_STANDARD":11}
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        run: echo ${{ matrix.configuration.os }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.configuration.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.configuration.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
      